In [12]:
import tensorflow as tf

feat_value = tf.constant([
                            [1., 1., 25.],
                            [1., 1., 26.]
]) # 输入特征的value，m * F

feat_index = tf.constant([
                    [0, 2, 4],
                    [1, 3, 4]
])

one_order_weight = tf.constant([[0.1],
                               [0.2],
                               [0.3],
                               [0.4],
                               [0.5]]) # feat_size * 1

# 一阶特征unit
one_order = tf.nn.embedding_lookup(one_order_weight, feat_index) # 应该是 m * F * 1
feat_value = tf.reshape(feat_value, shape=[-1, 3, 1]) # 将feat_value也变成 m * F * 1

with tf.Session() as sess:
    print(sess.run(one_order))
    print(sess.run(feat_value))
    
print("乘法后")
one_order = tf.multiply(one_order, feat_value)
one_order_res = tf.reduce_sum(one_order, 2)
with tf.Session() as sess:
    print(sess.run(one_order))
    print(sess.run(one_order_res))



[[[ 0.1       ]
  [ 0.30000001]
  [ 0.5       ]]

 [[ 0.2       ]
  [ 0.40000001]
  [ 0.5       ]]]
[[[  1.]
  [  1.]
  [ 25.]]

 [[  1.]
  [  1.]
  [ 26.]]]
乘法后
[[[  0.1       ]
  [  0.30000001]
  [ 12.5       ]]

 [[  0.2       ]
  [  0.40000001]
  [ 13.        ]]]
[[  0.1          0.30000001  12.5       ]
 [  0.2          0.40000001  13.        ]]


In [20]:
logits = tf.constant([
                            [1., 1., 25.],
                            [1., 1., 26.]
])
labels = tf.constant([
    [0, 0, 1],
    [1, 0, 0]
])
# softmax = tf.nn.softmax(logits)
loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels)
with tf.Session() as sess:
    print(sess.run(softmax))
    print(sess.run(tf.reduce_sum(softmax, 1)))
    print(sess.run(loss))

[[  3.77513437e-11   3.77513437e-11   1.00000000e+00]
 [  1.38879437e-11   1.38879437e-11   1.00000000e+00]]
[ 1.  1.]
[  0.  25.]
